sensor_kit_base_link:
  velodyne_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  velodyne_left_base_link:
    x: -0.140421
    y: 0.858753
    z: -0.150850
    roll: -0.149272
    pitch: 0.616655
    yaw: -0.305979
  velodyne_right_base_link:
    x: -0.132011
    y: -0.812099
    z: -0.145085
    roll: -0.036198
    pitch: 0.676989
    yaw: -0.048805
  gnss_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  livox_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
